mvcTemplate/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using mvc.Data;
using mvc.Models;
using mvc.Services;


namespace mvc.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserService _userService;

        public EventController(ApplicationDbContext context, UserService userService)
        {
            _context = context;
            _userService = userService;
        }

        public ActionResult Index()
        {
            var events = _context.Events;
            return View(events);
        }

        public async Task<IActionResult> Show(int id)   
        {
            var eventItem = await _context.Events.FindAsync(id);
            if (eventItem == null)
            {
                return NotFound();
            }

            var students = await _userService.GetStudentsInscribedAsync(id);
            ViewBag.Students = students;

            return View(eventItem);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Event newEvent)
        {
            if (ModelState.IsValid)
            {
                _context.Events.Add(newEvent);
                _context.SaveChanges();
                TempData["Message"] = "Événement créé avec succès.";
                return RedirectToAction("Index");
            }
            return View(newEvent);
        }

        public ActionResult Delete(int id)
        {
            var existingEvent = _context.Events.Find(id);
            _context.Events.Remove(existingEvent);
            _context.SaveChanges();
            TempData["Message"] = "Événement supprimé avec succès.";
            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            var curreneEvent = _context.Events.Find(id);
            return View(curreneEvent);
        }

        [HttpPost]
        public ActionResult Update(Event currentEvent)
        {
            Event currentEventToUpdate = _context.Events.Find(currentEvent.Id);
            currentEventToUpdate.Title = currentEvent.Title;
            currentEventToUpdate.Description = currentEvent.Description;
            currentEventToUpdate.EventDate = currentEvent.EventDate;
            currentEventToUpdate.MaxParticipants = currentEvent.MaxParticipants;
            currentEventToUpdate.Location = currentEvent.Location;
            _context.SaveChanges();
            TempData["Message"] = "Événement modifié avec succès.";
            
            return RedirectToAction("Index");
        }
    }
}

mvcTemplate/Controllers/StudentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{
    public class StudentController : Controller
    {

        private readonly UserManager<Student> _userManager;
        private readonly ApplicationDbContext _context;
        
        public StudentController(ApplicationDbContext context, UserManager<Student> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            var students = _context.Students;
            return View(students);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(StudentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new Student
            {
                UserName = model.Lastname + model.Firstname,
                Email = model.Email,
                Firstname = model.Firstname,
                Lastname = model.Lastname,
                Age = model.Age,
                FirstConnection = true,
                IsStudent = true
            };

            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        public IActionResult Show(string id)
        {
            var student = _context.Students.Find(id);
            return View(student);
        }

        public  IActionResult Delete(string id)
        {
            var student = _context.Students.Find(id);
            _context.Students.Remove(student);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

mvcTemplate/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ApplicationDbContext _context;
    
        public TeacherController(ApplicationDbContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            var teachers = _context.Teachers;
            return View(teachers);
        }

        public ActionResult Delete(string id)
        {
            var teacher = _context.Teachers.Find(id);
            _context.Teachers.Remove(teacher);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Show(string id)
        {
            var teacher = _context.Teachers.Find(id);
            return View(teacher);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            _context.Teachers.Add(teacher);

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Update(string id)
        {
            var teacher = _context.Teachers.Find(id);
            return View(teacher);
        }

        [HttpPost]
        public ActionResult Update(Teacher teacher)
        {
            Teacher teacherToUpdate = _context.Teachers.Find(teacher.Id);
            teacherToUpdate.Firstname = teacher.Firstname;
            teacherToUpdate.Lastname = teacher.Lastname;
            teacherToUpdate.Age = teacher.Age;
            teacherToUpdate.Matter = teacher.Matter;
            teacherToUpdate.Langage = teacher.Langage;
            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }
    }
}

mvcTemplate/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc;

@inject mvc.Services.UserService UserService
@inject SignInManager<Teacher> SignInManager
@inject UserManager<Teacher> UserManager
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc.styles.css" asp-append-version="true" />
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Campus Event</a>
                        </li>
                        @if (await UserService.IsTeacherAsync())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Event</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>